// packages/examples/react-theme/src/App.js
// import logo from './logo.svg';
import './App.css';

function App() {
  let app = null;
  // 加载自身依赖的插件
  // const mountSubWidget = async () => {
  //   const subData = await window.freelogApp.getSubDep();
  //   subData.subDep.some(async (sub, index) => {
  //     if (index === 1) return true;
  //     app = await window.freelogApp.mountWidget(
  //       sub,
  //       document.getElementById("freelog-single2"),
  //       subData,
  //       "",
  //       "",
  //       "http://localhost:7001"
  //     );
  //     // 插件加载完成
  //     app.mountPromise.then(() => {
  //       // 卸载与重载
  //       // app.unmount.then(() => {
  //       //   app.mount.then(() => {
  //       //   })
  //       // })
  //     })
  //   });
  // }
  const add = ()=>{
    app.getApi().changeMe()
  }
  // 加载展品类型的插件
  const mountExhibitWidget = async () => {
    const res = await window.freelogApp.getExhibitListByPaging({
      articleResourceTypes: "插件",
      isLoadVersionProperty: 1,
    });
    const widgets = res.data.data.dataList;
    widgets.some(async (widget, index) => {
      if (index === 1) return true;
      // widget.exhibitId = widget.exhibitId + '111'
      app = await window.freelogApp.mountWidget(
        widget,
        document.getElementById("freelog-single"),
        null,
        null,
        null,
        "http://localhost:7001"
      );
    });
  }
  mountExhibitWidget()
  return (
    <div className="App">
      <button onClick={add}>点我加1</button> 
      <div id="freelog-single"></div>
    </div>
  );
}
export default App;

// backup/freelog-single-theme/src/App.vue
<template>
  <div class="theme-main">
    <div id="freelog-single2"></div>
  </div>
</template>

<script>
export default {
  name: "freelog-document-app",
  data() {
    return {
      mount: false,
    };
  },
  computed: {},
  methods: {
    async getSub() {
      const subData = await window.freelogApp.getSubDep();
      subData.subDep.some(async (sub, index) => {
        if (index === 1) return true;
        const app = await window.freelogApp.mountWidget(
          sub,
          document.getElementById("freelog-single2"),
          subData,
          "",
          "",
        );
        app.mountPromise.then(()=>{
          // console.log(111111, app.getApi())
          // app.unmount.then(()=>{
          //   console.log(3333, app.getApi())
          //   app.mount.then(()=>{
          //     console.log(44444, app.getApi())
          //   })
          // })
        })
      
        // setTimeout(() => {
        //   app.unmount(() => {
        //     console.log(33333);
        //     app.mount();
        //   });
        // }, 1500);
      });
    },
  },
  async mounted() {
    window.freelogApp.onLogin(() => {
      window.location.reload();
    });
    !this.mount && this.getSub();
    this.mount = true;
  },
};
</script>

<style lang="less">
.theme-main {
  height: 100%;
  width: 100%;
}
#freelog-single {
  height: 100%;
  width: 100%;
}
</style>
