// packages/examples/react-theme/src/App.js
// import logo from './logo.svg';
import './App.css';

function App() {
  let app = null;
  // 加载自身依赖的插件
  // const mountSubWidget = async () => {
  //   const subData = await window.freelogApp.getSubDep();
  //   subData.subDep.some(async (sub, index) => {
  //     if (index === 1) return true;
  //     app = await window.freelogApp.mountWidget(
  //       sub,
  //       document.getElementById("freelog-single2"),
  //       subData,
  //       "",
  //       "",
  //       "http://localhost:7001"
  //     );
  //     // 插件加载完成
  //     app.mountPromise.then(() => {
  //       // 卸载与重载
  //       // app.unmount.then(() => {
  //       //   app.mount.then(() => {
  //       //   })
  //       // })
  //     })
  //   });
  // }
  const add = ()=>{
    app.getApi().changeMe()
  }
  // 加载展品类型的插件
  const mountExhibitWidget = async () => {
    const res = await window.freelogApp.getExhibitListByPaging({
      articleResourceTypes: "插件",
      isLoadVersionProperty: 1,
    });
    const widgets = res.data.data.dataList;
    widgets.some(async (widget, index) => {
      if (index === 1) return true;
      // widget.exhibitId = widget.exhibitId + '111'
      app = await window.freelogApp.mountWidget(
        widget,
        document.getElementById("freelog-single"),
        null,
        null,
        null,
        "http://localhost:7001"
      );
    });
  }
  mountExhibitWidget()
  return (
    <div className="App">
      <button onClick={add}>点我加1</button> 
      <div id="freelog-single"></div>
    </div>
  );
}
export default App;

// backup/freelog-game-theme/src/App.vue
<template >
  <div class="theme-main flex-row">
    <div class="w-300 br-1">
      <div v-for="a in gameList" :key="a.exhibitId" class="w-100x flex-column">
        <div @click="selectGame(a)" :class="['py-30 pl-40 bb-1 cur-pointer ', a.exhibitId === gameId? 'bg-active ' : '']" >
          {{a.exhibitName}}
        </div>
      </div>
    </div>
    <div id="freelog-single" class="mt-40"></div>
  </div>
</template>

<script>
export default {
  name: "freelog-document-app",
  data() {
    return {
      mount: false,
      gameName: '',
      gameId: '',
      gameList: [],
      widgetApp: null
    };
  },
  computed: {},
  methods: {
    selectGame(item){
      this.gameId  = item.exhibitId
      this.gameName = item.exhibitName
      this.widgetApp.unmount(()=>{
         this.widgetApp.mount()
      })
    },
    getGame(){
      return{
        gameId: this.gameId,
        gameName: this.gameName
      }
    },
    async getSub() {
      const subData = await window.freelogApp.getSubDep();
      subData.subDep.some(async (sub, index) => {
        if (index === 2) return true;
        if (index === 2) return true;
        this.widgetApp = await window.freelogApp.mountWidget(
          sub,
          document.getElementById("freelog-single"),
          subData,
          {
            getGame: this.getGame
          },
          "",
          // 'http://localhost:7107'
        );
        // let count = 0 const widgetApp = 
        // const a = setInterval(() => {
        //   count++
        //   widgetApp.unmount()
        //   setTimeout(() => widgetApp.mount(), 2000)
        //   if (count === 4) clearInterval(a)
        // }, 3000);
      });
    },
  },
  async mounted() {
    window.freelogApp.onLogin(() => {
      window.location.reload();
    });
    const res = await window.freelogApp.getExhibitListByPaging({
      skip: 0,
      limit: 20,
      articleResourceTypes: 'nesrom'
    });
    this.gameList = res.data.data.dataList
    this.gameId = res.data.data.dataList[0].exhibitId
    this.gameName = res.data.data.dataList[0].exhibitName
    !this.mount && this.getSub();
    this.mount = true;
  },
};
</script>

<style lang="scss">
.theme-main {
  height: 100%;
  width: 100%;
}
#freelog-single {
  height: 100%;
  width: 100%;
}
</style>
